### ISSUE TITLE
Fail to clone the repo

### ISSUE THREAD

**Issue by eiphy** [hwaseem04/Research-digest#3]
Hi, I'm unable to clone the repo as it reaches the data qato.

**Comment by hwaseem04** [comment]
The reason is that my GitHub account has exceeded `git lfs` limit (pre-trained model in this repo is uploaded with lfs). I am trying to make some alternatives, will update here soon.

**Comment by hwaseem04** [comment]
I have made a few changes. Now you have to download the model file from the drive link manually. Please let me know whether you are able to fork it now. 

I hope the issue would be solved. If not, reopen the issue
